INSERT INTO Courts(COURT_ID, NAME, ADDRESS, IMAGE, OPENING_HOUR, CLOSING_HOUR) VALUES(21, 'Testowy', 'Testowa 31', '21.jpg', 12, 18); 
INSERT INTO Courts(COURT_ID, NAME, ADDRESS, IMAGE, OPENING_HOUR, CLOSING_HOUR) VALUES(22, 'wvr', 'efwrg', '22.jpg', 10, 18); 
INSERT INTO Courts(COURT_ID, NAME, ADDRESS, IMAGE, OPENING_HOUR, CLOSING_HOUR) VALUES(23, 'qefwgr53rfw', 'efwre', '23.jpg', 12, 21); 
INSERT INTO Courts(COURT_ID, NAME, ADDRESS, IMAGE, OPENING_HOUR, CLOSING_HOUR) VALUES(25, '3qgevfarefv', 'ewfdscq', '25.jpg', 12, 18); 